### ISSUE TITLE
Arrow assets are not present in the repositoy

### ISSUE THREAD

**Issue by vortice3D** [shibuiwilliam/arcore-measurement#2]
Hi **Shibui**:

It seems to me that you're forgotten to include some graphic assets, the arrow ones.

Can you check that?

Best regards.

**Comment by vortice3D** [comment]
Hi again Shibui:

I suppose these kind of arrow will serve:

![arrow_1down](https://user-images.githubusercontent.com/1760601/78773642-d477dd00-7993-11ea-863e-829ab6386700.png)
![arrow_1up](https://user-images.githubusercontent.com/1760601/78773644-d5107380-7993-11ea-8e5b-396a49b76d70.png)
![arrow_10down](https://user-images.githubusercontent.com/1760601/78773646-d5a90a00-7993-11ea-9090-e4d14254bb8c.png)
![arrow_10up](https://user-images.githubusercontent.com/1760601/78773647-d641a080-7993-11ea-9229-808c28a84dd9.png)


I'm using with your code an all is working well.

Best regards.

**Comment by shibuiwilliam** [comment]
Sorry, I pushed them now.
Please take a look.

**Comment by vortice3D** [comment]
Thanks **shibuiwilliam**.

So, I'm closing this issue.
